INSERT INTO public.anthem ("motto", "content") VALUES 
('Himni i Flamurit',''),
('Einigkeit und Recht und Freiheit (Unidad, Justicia y Libertad)',''),
('Virtus Unita Fortior (en latín: La virtud es más fuerte unida)',''),
('Angola Avante!',''),
('Fair Antigua, We Salute Thee (Bella Antigua, te saludamos)',''),
('En Unión y Libertad',''),
('Mer Hayrenik (Nuestra Patria)',''),
('Advance Australia Fair (Avanza, Australia justa)',''),
('Land der Berge, Land am Strome (Tierra de montañas, tierra junto al río)',''),
('Odlar Yurdu (Tierra de Fuego)',''),
('March On, Bahamas (Marcha Adelante, Bahamas)',''),
('Bahrainona (Nuestro Baréin)',''),
('Joy Bangla (Victoria para Bengala)',''),
('Pride and Industry (Orgullo e industria)',''),
('Sub umbra floreo (Bajo la sombra florezco)',''),
('Fraternité, Justice, Travail (Fraternidad, Justicia, Trabajo)',''),
('My, bielarusy (Nosotros, bielorrusos)',''),
('La unión es la fuerza',''),
('Državna himna Bosne i Hercegovine (Himno Nacional de Bosnia y Herzegovina)',''),
('Fatshe leno la rona (Esta nuestra tierra)',''),
('Ordem e progresso (Orden y progreso)',''),
('Aldaayimun almuhsinun bialhudaa (Siempre mejorando con la guía de Dios)',''),
('Sǎedinenieto pravi silata (La unión hace la fuerza)',''),
('La Patrie ou la mort, nous vaincrons (Patria o muerte, venceremos)','');